# Generated by Django 3.0.4 on 2020-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0002_auto_20200324_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='dni',
            field=models.CharField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
    ]
