# Generated by Django 3.0.4 on 2020-04-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('dni', models.CharField(default=0, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('tlf', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('permisoConduccion', models.CharField(choices=[('T', 'Turismos'), ('B', 'Buses')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('J', 'Jubilado'), ('I', 'Infantil'), ('A', 'Adulto'), ('P', 'Pensionistas')], max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni', models.CharField(default=0, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('tlf', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=25)),
                ('plazas', models.PositiveIntegerField()),
                ('consumo', models.PositiveIntegerField()),
                ('motor', models.CharField(choices=[('E', 'Electric'), ('G', 'Gasolina'), ('D', 'Diesel')], max_length=1)),
                ('categoria', models.CharField(choices=[('T', 'Turismo'), ('B', 'Bus')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=25)),
                ('destino', models.CharField(max_length=25)),
                ('fechaHoraSalida', models.DateTimeField()),
                ('fechaHoraLlegada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'Accepted'), ('PE', 'Pending'), ('R', 'Rejected'), ('PA', 'Passed')], max_length=2)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movility.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=25)),
                ('destino', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField()),
                ('paradas', models.CharField(max_length=25)),
                ('conductor', models.CharField(max_length=25)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movility.Vehiculos')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rutas',
            constraint=models.UniqueConstraint(fields=('origen', 'destino', 'fecha'), name='unique_rutas'),
        ),
    ]
