# Generated by Django 3.0.4 on 2020-03-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni', models.CharField(default=0, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('tlf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=25)),
                ('plazas', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('motor', models.CharField(max_length=25)),
                ('categoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fechaHoraSalida', models.DateField()),
                ('fechaHoraLlegada', models.DateField()),
                ('estado', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movility.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.IntegerField()),
                ('destino', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('paradas', models.IntegerField()),
                ('conductor', models.CharField(max_length=50)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movility.Vehiculos')),
            ],
        ),
    ]
