# Generated by Django 3.0.4 on 2020-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='conductor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='destino',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='origen',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='paradas',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='destino',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='origen',
            field=models.CharField(max_length=25),
        ),
    ]
