# Generated by Django 3.0.4 on 2020-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaHoraLlegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaHoraSalida',
            field=models.DateTimeField(),
        ),
    ]
