# Generated by Django 3.0.4 on 2020-04-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0002_auto_20200401_2039'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
