# Generated by Django 3.0.4 on 2020-04-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0002_auto_20200402_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Passed'), ('R', 'Rejected'), ('A', 'Accepted')], max_length=2),
        ),
    ]
