# Generated by Django 3.0.4 on 2020-04-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0002_auto_20200330_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='idUsuario',
            field=models.ForeignKey(default='00000000T', on_delete=django.db.models.deletion.CASCADE, to='movility.Usuarios'),
        ),
    ]
