# Generated by Django 3.0.4 on 2020-04-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0003_auto_20200401_2055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
