# Generated by Django 3.0.4 on 2020-04-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0003_auto_20200402_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('coordenadas', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rutas',
            name='unique_rutas',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='paradas',
        ),
        migrations.AlterField(
            model_name='rutas',
            name='conductor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='movility.Conductores'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rutas', to='movility.Vehiculos'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('A', 'Accepted'), ('PA', 'Passed'), ('PE', 'Pending'), ('R', 'Rejected')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='movility.Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(default='00000000T', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='rutas',
            constraint=models.UniqueConstraint(fields=('origen', 'destino'), name='unique_rutas'),
        ),
        migrations.AddField(
            model_name='paradas',
            name='rutas',
            field=models.ManyToManyField(blank=True, related_name='paradas', to='movility.Rutas'),
        ),
        migrations.AddField(
            model_name='paradas',
            name='solicitudes',
            field=models.ManyToManyField(blank=True, related_name='paradas', to='movility.Solicitudes'),
        ),
    ]
