# Generated by Django 3.0.4 on 2020-04-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0003_auto_20200401_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaHoraLlegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaHoraSalida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movility.Usuarios'),
        ),
    ]
