# Generated by Django 3.0.4 on 2020-04-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0004_auto_20200401_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='idUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movility.Usuarios'),
        ),
    ]
