# Generated by Django 3.0.4 on 2020-04-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0004_auto_20200401_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='idUsuario',
            new_name='dni',
        ),
    ]
