# Generated by Django 3.0.4 on 2020-04-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0005_auto_20200401_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='dni',
            new_name='usuario',
        ),
    ]
