# Generated by Django 3.0.4 on 2020-04-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movility', '0005_auto_20200401_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('dni', models.CharField(default=0, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('tlf', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('permisoConduccion', models.CharField(choices=[('T', 'Turismos'), ('B', 'Buses')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('J', 'Jubilado'), ('I', 'Infantil'), ('A', 'Adulto'), ('P', 'Pensionistas')], max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('PA', 'Passed'), ('A', 'Accepted'), ('PE', 'Pending'), ('R', 'Rejected')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tlf',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='categoria',
            field=models.CharField(choices=[('T', 'Turismo'), ('B', 'Bus')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='consumo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='matricula',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='motor',
            field=models.CharField(choices=[('E', 'Electric'), ('G', 'Gasolina'), ('D', 'Diesel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='plazas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='rutas',
            constraint=models.UniqueConstraint(fields=('origen', 'destino', 'fecha'), name='unique_rutas'),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
